import random


ADJECTIVES = [
    "Cyber",
    "Shadow",
    "Neon",
    "Void",
    "Iron",
    "Gold",
    "Deadly",
    "Silent",
    "Atomic",
    "Hyper",
    "Mega",
    "Ultra",
    "Epic",
    "Primal",
    "Chaos",
    "Frost",
    "Flame",
    "Storm",
    "Electric",
    "Dark",
    "Light",
    "Swift",
    "Heavy",
    "Elite",
    "Radical",
    "Wild",
    "Cursed",
    "Blessed",
    "Ancient",
    "Future",
    "Alpha",
    "Omega",
    "Salty",
    "Toxic",
    "Based",
    "Lunar",
    "Solar",
    "Cosmic",
    "Astral",
    "Hidden",
    "Broken",
    "Radiant",
    "Vivid",
    "Mighty",
    "Little",
    "Big",
    "Grand",
    "Master",
    "Inferno",
    "Glacial",
    "Static",
    "Voltaic",
    "Ethereal",
    "Phantom",
    "Rogue",
    "Feral",
    "Savage",
    "Gilded",
    "Rusty",
    "Shiny",
    "Clumsy",
    "Drunken",
    "Zen",
    "Grim",
    "Bloody",
    "Icy",
    "Molten",
    "Vortex",
    "Plasma",
    "Quantum",
    "Nano",
    "Binary",
    "Cobalt",
    "Crimson",
    "Amber",
    "Violet",
    "Emerald",
    "Obsidian",
    "Stellar",
    "Galactic",
    "Infinite",
    "Zero",
    "Final",
    "Last",
    "First",
    "Pro",
    "Casual",
    "Hardcore",
    "Stealthy",
    "Vicious",
    "Brutal",
    "Mythic",
    "Legendary",
]


NOUNS = [
    "Hunter",
    "Slayer",
    "Runner",
    "Walker",
    "Gazer",
    "Stalker",
    "Knight",
    "Rogue",
    "Panda",
    "Cat",
    "Dog",
    "Hippo",
    "Glitch",
    "Pixel",
    "Viper",
    "Ghost",
    "Echo",
    "King",
    "Queen",
    "Lord",
    "Master",
    "Noob",
    "Pro",
    "Goblin",
    "Wraith",
    "Titan",
    "Pilot",
    "Crasher",
    "Masher",
    "Striker",
    "Blade",
    "Bow",
    "Fist",
    "Shield",
    "Guardian",
    "Warrior",
    "Soldier",
    "Merc",
    "Reaper",
    "Spirit",
    "Demon",
    "Angel",
    "Beast",
    "Monster",
    "Kraken",
    "Dragon",
    "Wolf",
    "Fox",
    "Panda",
    "Tiger",
    "Bear",
    "Eagle",
    "Hawk",
    "Raven",
    "Falcon",
    "Snake",
    "Spider",
    "Scorpion",
    "Wasp",
    "Bee",
    "Ant",
    "Bug",
    "Beetle",
    "Moth",
    "Badger",
    "Otter",
    "Raccoon",
    "Sloth",
    "Samurai",
    "Ninja",
    "Monk",
    "Mage",
    "Wizard",
    "Cleric",
    "Druid",
    "Brawler",
    "Thumper",
    "Thwacker",
    "Bopper",
    "Basher",
    "Zapper",
    "Laser",
    "Rocket",
    "Bomb",
    "Spark",
    "Bolt",
    "Pulse",
    "Wave",
    "Aura",
    "Nova",
    "Star",
    "Moon",
    "Sun",
]


DECORATIONS = [
    "_99",
    "XP",
    "TV",
    "YT",
    "_",
    "xX",
    "77",
    "PRO",
    "007",
    "_Main",
    "Official",
    "Live",
]


UNIQUE_NAMES = [
    "System32",
    "NullPointer",
    "Admin_Clone",
    "Priesty_Fan",
    "Manny_Simp",
    "Luna_Enjoyer",
    "Jax_Protege",
    "BlueBerry",
    "GreenTea",
    "CoffeeAddict",
    "MissingNo",
    "Rift_Walker_One",
    "The_Algorithm",
    "Bug_Reporter",
    "Daily_Job_Grinder",
    "Chaos_Addict",
    "Merch_Collector",
    "One_Small_Step",
    "Not_A_Bot",
    "Bot_9000",
    "Human_Sim",
    "Definitely_Real_Player",
    "Pro",
    "Brawler",
]


def get_random_bot_name():
    roll = random.random()

    if roll < 0.05:
        return random.choice(UNIQUE_NAMES)

    if random.random() < 0.7:

        base_name = f"{random.choice(ADJECTIVES)}{random.choice(NOUNS)}"
    else:

        base_name = f"{random.choice(NOUNS)}{random.choice(NOUNS)}"

    if random.random() < 0.2:
        deco = random.choice(DECORATIONS)
        if deco == "xX":
            base_name = f"xX_{base_name}_Xx"
        elif deco == "_":

            adj = random.choice(ADJECTIVES)
            noun = random.choice(NOUNS)
            base_name = f"{adj}_{noun}"
        else:
            base_name = f"{base_name}{deco}"

    return base_name


if __name__ == "__main__":
    for i in range(10):
        print(get_random_bot_name())
